#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HackAtHomeClient.Resource", IsApplication=true)]

namespace HackAtHomeClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HackAtHome.CustomAdapters.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.CustomAdapters.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::HackAtHome.Entities.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.Entities.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::HackAtHome.SAL.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.SAL.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int iconAndroid = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050010
			public const int button1 = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int buttonValidar = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int detailDescription = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int detailStatus = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int editTextEmail = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int editTextPassword = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int evidenceStatus = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int evidenceTitle = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int imageView1 = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int linearLayout2 = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int listView1 = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int textView1 = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int textViewDescriptionEvidence = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int textViewEvidence = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int textViewUserFullName = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int userFullNameDetail = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DetailEvidence = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Evidences = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EvidencesItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Email = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int Evidence = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Password = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Validate = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int description = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
